version: "3.9"

services:
  waha:
    image: devlikeapro/waha:latest
    ports:
      - "3000:3000"
    environment:
      WAHA_ADMIN_USERNAME: admin
      WAHA_ADMIN_PASSWORD: admin123
      WAHA_BASE_URL: https://waha-visual.up.railway.app  # <- Edite esse depois que criar na Railway
      WAHA_DB_PATH: /data/waha.db
    volumes:
      - waha-data:/data

volumes:
  waha-data:
